/**
 * поля строго как в БД!
 */


export const products = [
  { id: 1, name: "Кофемашина", description: "Автоматическая", price: 34999, category: "Бытовая техника", inStock: 20 },
  { id: 2, name: "Ноутбук", description: "Игровой", price: 89999, category: "Электроника", inStock: 20 },
  { id: 3, name: "Смартфон", description: "AMOLED-дисплей", price: 45999, category: "Мобильные устройства", inStock: 20 },
  { id: 4, name: "Пылесос", description: "Робот-пылесос", price: 29999, category: "Бытовая техника", inStock: 20 },
  { id: 5, name: "Монитор", description: "4K UHD", price: 27999, category: "Электроника", inStock: 20 },
  { id: 6, name: "Клавиатура", description: "Механическая", price: 7999, category: "Аксессуары", inStock: 20 },
  { id: 7, name: "Мышь", description: "Беспроводная", price: 2999, category: "Аксессуары", inStock: 20 },
  { id: 8, name: "Часы", description: "Умные часы", price: 11999, category: "Гаджеты", inStock: 20 },
  { id: 9, name: "Телевизор", description: "55 дюймов", price: 55999, category: "Бытовая техника", inStock: 20 },
  { id: 10, name: "Наушники", description: "Шумоподавление", price: 14999, category: "Аудио", inStock: 20 },
  { id: 11, name: "Стиральная машина", description: "Фронтальная загрузка", price: 44999, category: "Бытовая техника", inStock: 15 },
  { id: 12, name: "Микроволновка", description: "С грилем", price: 12999, category: "Бытовая техника", inStock: 25 },
  { id: 13, name: "Фен", description: "Ионизация", price: 4999, category: "Красота", inStock: 30 },
  { id: 14, name: "Тостер", description: "На 4 ломтика", price: 3999, category: "Бытовая техника", inStock: 18 },
  { id: 15, name: "Холодильник", description: "Двухкамерный", price: 67999, category: "Бытовая техника", inStock: 10 },
  { id: 16, name: "Геймпад", description: "Беспроводной", price: 4999, category: "Игровые устройства", inStock: 22 },
  { id: 17, name: "Колонки", description: "Bluetooth", price: 9999, category: "Аудио", inStock: 28 },
  { id: 18, name: "Планшет", description: "10-дюймовый дисплей", price: 34999, category: "Электроника", inStock: 12 },
  { id: 19, name: "Электронная книга", description: "E-Ink дисплей", price: 14999, category: "Гаджеты", inStock: 17 },
  { id: 20, name: "Портативный аккумулятор", description: "10000 мАч", price: 2999, category: "Аксессуары", inStock: 50 },
  { id: 21, name: "Видеокарта", description: "RTX 3060", price: 54999, category: "Компьютерное железо", inStock: 8 },
  { id: 22, name: "Модем", description: "4G LTE", price: 4999, category: "Сети", inStock: 19 },
  { id: 23, name: "Роутер", description: "Wi-Fi 6", price: 6999, category: "Сети", inStock: 14 },
  { id: 24, name: "Видеорегистратор", description: "Full HD", price: 8999, category: "Автомобильные аксессуары", inStock: 20 },
  { id: 25, name: "Шлем виртуальной реальности", description: "VR", price: 32999, category: "Игровые устройства", inStock: 5 },
  { id: 26, name: "Фитнес-браслет", description: "Пульсометр", price: 7999, category: "Гаджеты", inStock: 30 },
  { id: 27, name: "Микрофон", description: "Конденсаторный", price: 9999, category: "Аудио", inStock: 13 },
  { id: 28, name: "Принтер", description: "Лазерный", price: 19999, category: "Офисная техника", inStock: 9 },
  { id: 29, name: "Сканер", description: "A4", price: 12999, category: "Офисная техника", inStock: 11 },
  { id: 30, name: "Мультиварка", description: "12 программ", price: 15999, category: "Бытовая техника", inStock: 18 },
  { id: 31, name: "Термометр", description: "Инфракрасный", price: 2999, category: "Медицина", inStock: 30 },
  { id: 32, name: "Утюг", description: "Паровой", price: 4999, category: "Бытовая техника", inStock: 25 },
  { id: 33, name: "Игровое кресло", description: "Эргономичное", price: 29999, category: "Мебель", inStock: 7 },
  { id: 34, name: "Кофеварка", description: "Капельная", price: 5999, category: "Бытовая техника", inStock: 10 },
  { id: 35, name: "Зарядное устройство", description: "Быстрая зарядка", price: 1999, category: "Аксессуары", inStock: 40 },
  { id: 36, name: "Пауэрбанк", description: "20000 мАч", price: 4999, category: "Аксессуары", inStock: 35 },
  { id: 37, name: "Проектор", description: "HD", price: 25999, category: "Электроника", inStock: 15 },
  { id: 38, name: "Коврик для мыши", description: "Игровой", price: 999, category: "Аксессуары", inStock: 50 },
  { id: 39, name: "Флешка", description: "128 ГБ", price: 1999, category: "Накопители", inStock: 60 },
  { id: 40, name: "SSD", description: "1 ТБ", price: 7499, category: "Компьютерное железо", inStock: 20 },
  { id: 41, name: "HDD", description: "2 ТБ", price: 5999, category: "Накопители", inStock: 15 },
  { id: 42, name: "Игровая консоль", description: "PlayStation 5", price: 54999, category: "Игровые устройства", inStock: 6 },
  { id: 43, name: "Массажер", description: "Шейный", price: 9999, category: "Массажное оборудование", inStock: 18 },
  { id: 44, name: "Кулер для процессора", description: "RGB", price: 3499, category: "Компьютерное железо", inStock: 15 },
  { id: 45, name: "Акустическая система", description: "2.1", price: 19999, category: "Аудио", inStock: 9 },
  { id: 46, name: "Мультипечь", description: "С конвекцией", price: 15999, category: "Бытовая техника", inStock: 20 },
  { id: 47, name: "Электрическая зубная щетка", description: "С таймером", price: 4999, category: "Гигиена", inStock: 20 },
  { id: 48, name: "Умная колонка", description: "С голосовым помощником", price: 12999, category: "Гаджеты", inStock: 14 },
  { id: 49, name: "Смарт-ТВ приставка", description: "4K", price: 5999, category: "Гаджеты", inStock: 25 },
  { id: 50, name: "Рюкзак", description: "Для ноутбука", price: 2999, category: "Аксессуары", inStock: 50 },
  { id: 51, name: "Калькулятор", description: "Научный", price: 1499, category: "Канцелярия", inStock: 30 },
  { id: 52, name: "Стабилизатор напряжения", description: "500 Вт", price: 9999, category: "Электроника", inStock: 10 },
  { id: 53, name: "Электросамокат", description: "Складной", price: 34999, category: "Гаджеты", inStock: 5 },
  { id: 54, name: "Освежитель воздуха", description: "С ароматами", price: 1999, category: "Домашний уют", inStock: 40 },
  { id: 55, name: "Электрогриль", description: "Настольный", price: 17999, category: "Кухонная техника", inStock: 12 },
  { id: 56, name: "Веб-камера", description: "Full HD", price: 7999, category: "Аксессуары", inStock: 18 },
  { id: 57, name: "Электронный термометр", description: "Цифровой", price: 999, category: "Гигиена", inStock: 25 },
  { id: 58, name: "Кресло руководителя", description: "С кожаной обивкой", price: 24999, category: "Мебель", inStock: 8 },
  { id: 59, name: "Тепловентилятор", description: "С термостатом", price: 5999, category: "Обогреватели", inStock: 15 },
  { id: 60, name: "Увлажнитель воздуха", description: "Ультразвуковой", price: 8999, category: "Домашний уют", inStock: 22 },
];

export const categories = [
  { id: 1, name: "Бытовая техника", description: "Техника для дома" },
  { id: 2, name: "Электроника", description: "Компьютеры и гаджеты" },
];
